# Site Info
title: "次生进化"
slogan: "关注人工智能、学习科学、价值投资"
baseurl: ''
weburl: 'https://yifeitao.com'
author: 'yifeitao'
logo: '/assets/images/logo.jpg'

# Site configurations
plugins:
  - jekyll-feed
markdown: kramdown
kramdown:  
  input: GFM
  syntax_highlighter: rouge

excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
recent_post: 10
permalink: '/:year//:month/:title'

# Navigation (2nd level links supported)
nav:
  第二次进化:
    - '/'
    - { 归档: '/archive/' }
    - { 分类: '/categories/' }
    - { 标签: '/tags/' }
    - { 搜索: '/search/' }
    - { 关于: '/about/' }

# Add your friend-links
# friends:
#   A: 'link_A'
#   B: 'link_B'

# Relative path compatibility (JS hack, experimental and buggy feature)
# relative_path: true

# Where are tags and categories displayed
tag_page: '/tags/'
category_page: '/categories/'

# Comments provider config
comments_provider: vssue
owner: yifeitao
repo: yifeitao.github.io
vssue_clientId: 1d4ebc70fd877e40b5fa
vssue_clientSecret: 209ea95a15aa7c9ae6eae6abcdadc2200f7dedbe
#livere_uid: MTAyMC8zNDI2NS8xMDgwMg==
#disqus_shortname: yifeitao

# Analytics provider config
analytics_provider: google
google_analytics: UA-98784328-1

# reveal.js slide template
reveal_path: https://cdn.bootcss.com/reveal.js/3.4.1/

# additional message in sidebar
addition: '</br>念念不忘，必有回响'

# Reading Files
include:
  - .htaccess
  - _pages